name: Update AoC Badges 2023
on:
  workflow_dispatch:
  push:
    paths:
      - src/main/kotlin/aoc2023/*

jobs:
  update:
    uses: ./.github/workflows/aoc_badge.yml
    secrets: inherit
    with:
      year: 2023
      starsRegex: '(?<=\[stars2023\]\(https:\/\/img\.shields\.io\/badge\/stars%20â­-)[0-9]+(?=-yellow)'
      daysCompletedRegex: '(?<=\[days2023\]\(https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)'