name: Update AoC Badges 2022
on:
  workflow_dispatch:
  push:
    paths:
      - src/aoc2022/*

jobs:
  update:
    uses: ./.github/workflows/aoc_badge.yml
    with:
      year: 2022
      starsRegex: '(?<=\[stars2022\]\(https:\/\/img\.shields\.io\/badge\/stars%20â­-)[0-9]+(?=-yellow)'
      daysCompletedRegex: '(?<=\[days2022\]\(https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)'